name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - ipyleaflet
  - ipywidgets
  - datetime
  - bqplot
  - seaborn
  - cartopy